name: manifest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
